version: '3.3'
services:
  i_socket_node:
    container_name: 'i_socket_node'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
