require('dotenv').config()
const express = require('express')
const app = express()
const server = require('http').createServer(app)
const route = require('./route')
app.use(route)
const port = parseInt(process.env.PORT || 3003)
server.listen(port)